In [22]:
import numpy as np
import pandas as pd
from fantasy_baseball_draft.stats import StatSynonyms, StatCalculator

In [2]:
hit_path = 'hitters_2025_postdraft.csv'
pitch_path = 'pitchers_2025_postdraft.csv'
hitters = pd.read_csv(hit_path).pipe(StatSynonyms().normalize_df).drop(columns='Unnamed: 18')
hitters.head()

,Avail,Player,AB,R,H,1B,2B,3B,HR,RBI,BB,K,SB,CS,BA,OBP,SLG,Rank
0,Cackleberry Czars,"Shohei Ohtani P,U | LAD",546.0,125.0,172.0,85.0,37.0,6.0,44.0,117.0,72.0,137.0,45.0,5.0,0.315,0.402,0.646,1.0
1,Duane Kuiper Belt Sucks,Aaron Judge CF | NYY,521.0,112.0,162.0,76.0,35.0,2.0,49.0,126.0,106.0,177.0,8.0,1.0,0.311,0.434,0.668,2.0
2,Witt’s End,Bobby Witt SS | KC,578.0,112.0,195.0,114.0,42.0,8.0,31.0,100.0,56.0,117.0,28.0,11.0,0.337,0.400,0.599,3.0
3,Walk-In Closets,Jose Ramirez 3B | CLE,553.0,102.0,161.0,85.0,36.0,4.0,36.0,106.0,61.0,80.0,34.0,6.0,0.291,0.361,0.566,4.0
4,Bilgola-Balgowlah Bluedragons Modern Baseball ...,Francisco Lindor SS | NYM,582.0,111.0,164.0,90.0,37.0,4.0,33.0,96.0,63.0,130.0,28.0,4.0,0.282,0.358,0.529,5.0

In [9]:
team = 'Omak'
team_mask = hitters['Avail'].str.match(team)
#player_mask = hitters['Player'].str.startswith('Alej')
team_hitters = hitters[hitters['Avail'].str.match(team)].drop([618, 2808, 347])
print(team_hitters.sum())
print(team_hitters.sum().H / team_hitters.sum().AB)
# StatCalculator().calculate_metrics(team_hitters.sum(), ['BA'])
team_hitters

Avail     Omak Wrong PlayersOmak Wrong PlayersOmak Wrong...
Player    Juan Soto RF | NYMVladimir Guerrero 1B,3B | TO...
AB                                                   4664.0
R                                                     740.0
H                                                    1295.0
1B                                                    781.0
2B                                                    267.0
3B                                                     38.0
HR                                                    209.0
RBI                                                   709.0
BB                                                    557.0
K                                                    1121.0
SB                                                    104.0
CS                                                     26.0
BA                                                     2.77
OBP                                                   3.567
SLG                                                   4.817
Rank                                                 1171.0
dtype: object
0.27765866209262435

,Avail,Player,AB,R,H,1B,2B,3B,HR,RBI,BB,K,SB,CS,BA,OBP,SLG,Rank
5,Omak Wrong Players,Juan Soto RF | NYM,539.0,114.0,162.0,87.0,32.0,6.0,37.0,104.0,100.0,122.0,8.0,4.0,0.301,0.412,0.588,6.0
25,Omak Wrong Players,"Vladimir Guerrero 1B,3B | TOR",556.0,84.0,173.0,107.0,35.0,1.0,30.0,95.0,59.0,93.0,3.0,2.0,0.311,0.381,0.540,26.0
56,Omak Wrong Players,"Brandon Lowe 1B,2B | TB",487.0,78.0,125.0,72.0,23.0,3.0,27.0,81.0,51.0,133.0,9.0,1.0,0.257,0.332,0.482,62.0
58,Omak Wrong Players,James Wood LF | WAS,466.0,72.0,127.0,78.0,23.0,8.0,18.0,71.0,55.0,153.0,19.0,9.0,0.273,0.355,0.472,64.0
59,Omak Wrong Players,Xavier Edwards SS | MIA,417.0,64.0,128.0,91.0,22.0,8.0,7.0,49.0,44.0,88.0,35.0,6.0,0.307,0.369,0.448,65.0
93,Omak Wrong Players,Paul Goldschmidt 1B | NYY,492.0,68.0,124.0,71.0,27.0,1.0,25.0,70.0,50.0,158.0,9.0,1.0,0.252,0.322,0.463,104.0
107,Omak Wrong Players,Will Smith C | LAD,453.0,78.0,121.0,78.0,23.0,2.0,18.0,77.0,56.0,94.0,2.0,1.0,0.267,0.354,0.446,121.0
162,Omak Wrong Players,Jonathan India 2B | KC,410.0,68.0,109.0,71.0,23.0,2.0,13.0,51.0,52.0,90.0,11.0,1.0,0.266,0.358,0.427,209.0
190,Omak Wrong Players,Junior Caminero 3B | TB,423.0,53.0,109.0,65.0,24.0,2.0,18.0,60.0,42.0,100.0,6.0,1.0,0.258,0.330,0.452,253.0
193,Omak Wrong Players,J.J. Bleday CF | ATH,421.0,61.0,117.0,61.0,35.0,5.0,16.0,51.0,48.0,90.0,2.0,0.0,0.278,0.354,0.499,261.0

In [27]:
cols_to_show = ['Name', 'G', "PA", 'H', 'HR', "R", 'RBI', 'BB', 'SB', 'AVG', 'MLBAMID']
steamer_hitters = pd.read_csv('fangraphs_hitters_projections_2025.csv')#.astype({'MLBAMID': np.int64})
steamer_hitters.query('Name.str.startswith("Vl")')[cols_to_show]
steamer_hitters.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4140 entries, 0 to 4139
Data columns (total 74 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       4140 non-null   object
 1   Team       2773 non-null   object
 2   G          4140 non-null   float64
 3   PA         4140 non-null   float64
 4   AB         4140 non-null   float64
 5   H          4140 non-null   float64
 6   1B         4140 non-null   float64
 7   2B         4140 non-null   float64
 8   3B         4140 non-null   float64
 9   HR         4140 non-null   float64
 10  R          4140 non-null   float64
 11  RBI        4140 non-null   float64
 12  BB         4140 non-null   float64
 13  IBB        4140 non-null   float64
 14  SO         4140 non-null   float64
 15  HBP        4140 non-null   float64
 16  SF         4140 non-null   float64
 17  SH         4140 non-null   float64
 18  GDP        0 non-null      float64
 19  SB         4140 non-null   float64
 20  CS         4140 non-null   float64
 21  AVG        4140 non-null   float64
 22  BB%        4140 non-null   float64
 23  K%         4140 non-null   float64
 24  BB/K       4140 non-null   float64
 25  OBP        4140 non-null   float64
 26  SLG        4140 non-null   float64
 27  wOBA       4140 non-null   float64
 28  OPS        4140 non-null   float64
 29  ISO        4140 non-null   float64
 30  Spd        4140 non-null   float64
 31  BABIP      4140 non-null   float64
 32  UBR        4140 non-null   float64
 33  wSB        4140 non-null   float64
 34  wRC        4140 non-null   float64
 35  wRAA       4140 non-null   float64
 36  wRC+       4140 non-null   float64
 37  BsR        4140 non-null   float64
 38  Fld        4140 non-null   float64
 39  Off        4140 non-null   float64
 40  Def        4140 non-null   float64
 41  WAR        4140 non-null   float64
 42  ADP        4140 non-null   float64
 43  InterSD    0 non-null      float64
 44  InterSK    0 non-null      float64
 45  IntraSD    0 non-null      float64
 46  Vol        0 non-null      float64
 47  Skew       0 non-null      float64
 48  Dim        0 non-null      float64
 49  FPTS       4140 non-null   float64
 50  FPTS/G     1220 non-null   float64
 51  SPTS       4140 non-null   float64
 52  SPTS/G     1220 non-null   float64
 53  P10        1353 non-null   float64
 54  P20        1353 non-null   float64
 55  P30        1353 non-null   float64
 56  P40        1353 non-null   float64
 57  P50        1353 non-null   float64
 58  P60        1353 non-null   float64
 59  P70        1353 non-null   float64
 60  P80        1353 non-null   float64
 61  P90        1353 non-null   float64
 62  TT10       1353 non-null   float64
 63  TT20       1353 non-null   float64
 64  TT30       1353 non-null   float64
 65  TT40       1353 non-null   float64
 66  TT50       1353 non-null   float64
 67  TT60       1353 non-null   float64
 68  TT70       1353 non-null   float64
 69  TT80       1353 non-null   float64
 70  TT90       1353 non-null   float64
 71  NameASCII  4140 non-null   object
 72  PlayerId   4140 non-null   object
 73  MLBAMID    4139 non-null   float64
dtypes: float64(70), object(4)
memory usage: 2.3+ MB

In [4]:
set(pd.DataFrame({'a': []}))

{'a'}

In [8]:
pitchers = pd.read_csv(pitch_path).pipe(StatSynonyms().normalize_df).drop(columns='Unnamed: 18')
pitchers.head()
team_pitchers = pitchers[pitchers['Avail'].str.match(team)].drop([829, 192, 181, 151])
team_pitchers

,Avail,Player,IP,G,GS,QS,CG,W,L,S,BS,HD,K,BB,H,ERA,WHIP,Rank
13,Omak Wrong Players,Bowden Francis P | TOR,155.0,26.0,26.0,14.0,0.0,10.0,7.0,0.0,0.0,0.0,141.0,33.0,118.0,2.96,0.97,126.0
24,Omak Wrong Players,Hunter Greene P | CIN,173.0,30.0,30.0,15.0,0.0,11.0,6.0,0.0,0.0,0.0,198.0,56.0,150.0,3.54,1.19,155.0
33,Omak Wrong Players,Ronel Blanco P | HOU,180.0,32.0,32.0,17.0,1.0,12.0,8.0,0.0,0.0,0.0,179.0,66.0,154.0,3.55,1.22,181.0
63,Omak Wrong Players,Robert Suarez P | SD,61.0,68.0,0.0,0.0,0.0,2.0,2.0,35.0,7.0,3.0,52.0,15.0,43.0,2.80,0.95,255.0
78,Omak Wrong Players,Yusei Kikuchi P | LAA,168.0,30.0,30.0,11.0,0.0,8.0,9.0,0.0,0.0,0.0,185.0,54.0,155.0,3.59,1.24,293.0
95,Omak Wrong Players,Garrett Crochet P | BOS,118.0,26.0,26.0,10.0,0.0,10.0,6.0,0.0,0.0,0.0,158.0,26.0,117.0,4.27,1.21,338.0
99,Omak Wrong Players,Chad Green P | TOR,60.0,69.0,0.0,0.0,0.0,3.0,4.0,29.0,6.0,14.0,56.0,16.0,48.0,3.60,1.07,353.0
114,Omak Wrong Players,Tyler Holton P | DET,77.0,60.0,0.0,0.0,0.0,4.0,1.0,6.0,1.0,17.0,67.0,15.0,49.0,2.45,0.83,405.0

In [ ]:
StatCalculator().calculate_metrics(team_pitchers.sum(), ['ERA',])

KeyError: '1B'